
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
# File:		HPMProject_si4project_filelist.py
# Time:		2023/09/18 10:12:14
# Author:	hl-ally
# Version:	1.0
# Desc:

"""
import os
import sys
import json
from datetime import datetime


if __name__ == "__main__":
    print("start trans")

    if len(sys.argv) != 2:
        print("please input correct param")
        exit()
    
    fileName = sys.argv[1]
    print(fileName)

    # 打开json文件，并获取相关信息
    with open(fileName, "r") as f:
        datas = json.loads(f.read())
    datas = datas["target"]
    # print(type(datas))
    project_name = datas["name"]
    output_file = project_name + "_sifilelist.txt"

    # 获取.c文件
    sources = datas["sources"]
    sources = sources.split(",")
    # print(sources)
    
    # 获取.h文件
    includes = datas["includes"]
    includes = includes.split(",")
    # print(includes)
    include_files = []
    for inc_path in includes:
        if inc_path.endswith("."):
            inc_path = inc_path[:-2]
        print(inc_path)
        for root, dirs, files in os.walk(inc_path):
            for file in files:
                if file.endswith(".h"):
                    include_files.append(os.path.join(root, file))
    

        
    outputfile = open(output_file, 'w')
    outputfile.write('; Source Insight Project File List\n')
    outputfile.write('; Project Name: '+project_name+'\n')
    outputfile.write('; Generated by '+ __file__ + ' at '+datetime.now().strftime('%Y/%m/%d %H:%M:%S')+'\n')
    outputfile.write('; Version=4.00.xxxx\n')
    outputfile.write(';\n')
    outputfile.write('; Each line should contain either a file name, a wildcard, or a sub-directory name.\n')
    outputfile.write('; File paths are relative to the project source root directory.\n')
    outputfile.write(';\n')
    for src in sources:
        print(src)
        outputfile.write(src)
        outputfile.write("\n")

    for inc in include_files:
        print(inc)
        outputfile.write(inc.replace("\\", '/'))
        outputfile.write("\n")
    outputfile.close()
    